import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const translations = language === 'en' ? enTranslations : zhTranslations;
    const keys = key.split('.');
    let value: any = translations;
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// English translations
const enTranslations = {
  header: {
    home: 'Home',
    partners: 'Partners',
    solutions: 'Solutions',
    about: 'About',
    products: 'Products',
    caseStudies: 'Case Studies',
    contact: 'Contact',
    login: 'Login',
    getStarted: 'Get Started',
    loading: 'Loading...',
    noPartners: 'No partners available',
    iotConnectivity: 'IoT Connectivity',
    m2mPlatform: 'M2M Platform',
    deviceManagement: 'Device Management',
    analytics: 'Analytics & Insights',
    customSolutions: 'Custom Solutions',
  },
  hero: {
    companyName: 'ISL - Inclusive Information Services Limited',
    title1: 'Global IoT & M2M Connectivity,',
    title2: 'Engineered Locally',
    description: 'Powering millions of IoT devices across China, India, EU, USA, and Singapore with carrier-grade reliability',
    iotSolutions: 'IoT Solutions',
    m2mConnectivity: 'M2M Connectivity',
    support: '24/7 Support',
    scrollDown: 'Scroll Down',
  },
  about: {
    title: 'Global IoT & M2M Connectivity, Engineered Locally',
    subtitle1: 'We bridge the gap between global reach and local expertise, delivering seamless IoT connectivity across continents.',
    subtitle2: 'Trusted by enterprises worldwide, ISL powers millions of connected devices with carrier-grade reliability and regional compliance.',
    globalOperations: 'Global Operations',
    active: 'Active',
    ourValues: 'Our Values',
    compliance: 'Compliance',
    value1: 'Reliability: 99.9% uptime SLA backed by redundant networks',
    value2: 'Local Expertise: In-country regulatory compliance and support',
    value3: 'Innovation: Cutting-edge IoT solutions for evolving needs',
    value4: 'Transparency: Clear pricing with no hidden fees',
    miit: 'MIIT',
    miitDesc: 'China Ministry Approved',
    trai: 'TRAI',
    traiDesc: 'India Telecom Authority',
    ce: 'CE',
    ceDesc: 'European Conformity',
    fcc: 'FCC',
    fccDesc: 'USA Federal Certified',
    ctaTitle: 'Ready to Connect Globally?',
    ctaDesc: 'Book a 15-minute discovery call to discuss your IoT connectivity needs',
    bookCall: 'Book Discovery Call',
    china1: 'China',
    chinaLocation: 'Shanghai',
    china2: 'China',
    HKLocation: 'Hong Kong',
    india: 'India',
    indiaLocation: 'Mumbai & Delhi',
    eu: 'EU',
    euLocation: 'Stockholm',
    usa: 'USA',
    usaLocation: 'Chicago',
  },
  cta: {
    title: "Let's Connect Your IoT Ecosystem",
    description: 'Start your global IoT deployment with ISL. Contact us for a personalized consultation.',
    namePlaceholder: 'Your Name',
    emailPlaceholder: 'Email Address',
    companyPlaceholder: 'Company Name',
    submitButton: 'Request a Consultation',
    reachUs: 'Or reach us directly at:',
    contactInfo: 'INCLUSIVE-SALES@inclusive.com.cn',
  },
  solutions: {
    title: 'Enterprise IoT Solutions',
    subtitle: 'End-to-end connectivity solutions tailored for your IoT deployment needs',
    globalIotSim: 'Global IoT SIM',
    globalIotSimDesc: 'eUICC-enabled SIMs for seamless global roaming across 180+ countries',
    globalIotSimBenefit: 'One SIM, worldwide connectivity',
    privateApn: 'Private APN + VPN + InterCloud',
    privateApnDesc: 'Dedicated network tunnels with enterprise-grade security for sensitive IoT data',
    privateApnBenefit: 'Bank-level security for your devices',
    smsVoice: 'SMS & Voice for IoT',
    smsVoiceDesc: 'Two-way SMS and voice channels for device management and critical alerts',
    smsVoiceBenefit: 'Real-time device communication',
    chinaApproval: 'China Type-Approval & Whitelist',
    chinaApprovalDesc: 'Full MIIT certification and network whitelist service for China market entry',
    chinaApprovalBenefit: 'Fast-track China market access',
    indiaDlt: 'India DLT Onboarding',
    indiaDltDesc: 'Complete DLT registration bundle for TRAI-compliant promotional SMS campaigns',
    indiaDltBenefit: 'Launch SMS campaigns in 48 hours',
    learnMore: 'Learn More',
  },
  products: {
    title: 'Flexible Pricing Plans',
    subtitle: 'Choose the plan that fits your IoT deployment scale',
    prepaid: 'Pre-paid',
    postpaid: 'Post-paid',
    popular: 'Popular',
    getStarted: 'Get Started',
    customSolution: 'Need a custom solution?',
    contactSales: 'Contact our sales team',
    starterPack: 'Starter SIM Pack',
    volumePlans: 'Volume Plans',
    oemWhiteLabel: 'OEM White-Label SIM',
    managementPortal: 'Management Portal',
    perSim3Months: 'per SIM / 3 months',
    basedOnVolume: 'based on volume',
    perSimMoq: 'per SIM (10K+ MOQ)',
    withAllPlans: 'with all plans',
    included: 'Included',
    custom: 'Custom',
  },
  footer: {
    companyDesc: 'Leading provider of IoT M2M connectivity solutions for businesses worldwide.',
    services: 'Services',
    iotConnectivity: 'IoT Connectivity',
    m2mSolutions: 'M2M Solutions',
    networkSecurity: 'Network Security',
    dataManagement: 'Data Management',
    company: 'Company',
    aboutUs: 'About Us',
    careers: 'Careers',
    partners: 'Partners',
    contact: 'Contact',
    contactUs: 'Contact Us',
    whatsappSupport: 'WhatsApp Support',
    chinaOffice: 'China Office',
    chinaLocation: 'Shanghai, China',
    indiaOffice: 'India Office',
    indiaLocation: 'Mumbai & Delhi, India',
    euOffice: 'EU Office',
    euLocation: 'Amsterdam, Netherlands',
    copyright: '© 2025 Inclusive Information Services Limited. All rights reserved.',
  },
  caseStudy: {
    title: 'Customer Success Stories',
    subtitle: 'See how leading companies trust ISL for their global IoT deployments',
    backToHome: 'Back to Home',
    theChallenge: 'The Challenge',
    ourSolution: 'Our Solution',
    results: 'Results',
    contactUs: 'Contact Us',
    ev: {
      badge: 'Automotive',
      title: 'EV Telematics Success Story',
      shortTitle: "EV Telematics",
      subtitle: 'Real-time vehicle diagnostics and fleet management globally',
      metric1: 'Active SIMs',
      metric2: 'Countries',
      metric3: 'Uptime',
      metric4: '180 Countries',
      highlight: '99% uptime',
      challengeText1: 'A leading electric vehicle manufacturer needed a reliable, scalable IoT connectivity solution to support their rapidly global expansion. Their existing connectivity infrastructure was fragmented across multiple carriers, leading to coverage gaps, inconsistent performance, and complex billing.',
      challengeText2: 'The company required real-time vehicle diagnostics, over-the-air updates, and fleet management capabilities across 100+ countries, with seamless roaming and carrier-grade reliability.',
      solution1Title: 'Global Multi-Service-Provider-Supported SIM Cards',
      solution1Desc: 'Deployed eUICC-enabled SIM cards with multiple service providers supports, enabling automatic network switching for optimal coverage and cost efficiency across all operating regions.',
      solution2Title: 'Private APN & VPN Security',
      solution2Desc: 'Implemented enterprise-grade security with dedicated private APN and VPN tunnels to protect sensitive vehicle data and ensure secure over-the-air updates.',
      solution3Title: 'Real-Time Management Portal',
      solution3Desc: 'Provided comprehensive connectivity management platform with real-time diagnostics, usage analytics, and automated alerting for proactive issue resolution.',
      result1: '99% uptime across all markets, exceeding SLA requirements',
      result2: '40% reduction in connectivity costs through optimized carrier selection',
      result3: 'Seamless expansion of vehicles sales across continents without infrastructure changes',
      result4: 'Real-time diagnostics enabling predictive maintenance and reduced downtime',
      ctaTitle: 'Ready to Scale Your IoT Fleet?',
      ctaDesc: "Let's discuss how ISL can power your connected vehicle solution",
    },
    smartMeter: {
      badge: 'Energy',
      title: 'Smart Meter OEM Success Story',
      shortTitle: "Smart Meter OEM",
      subtitle: 'Low-power metering solution with extended device lifecycle',
      metric1: 'NB-IoT SIMs',
      metric2: 'Battery Life',
      metric3: 'Cost Reduction',
      metric4: '800K NB-IoT SIMs • 10-year battery',
      highlight: '50% cost reduction',
      challengeText1: 'A smart meter manufacturer needed an ultra-low-power connectivity solution that could support 10+ year battery life for remote utility metering deployments. Traditional cellular connectivity was too power-hungry and costly for large-scale meter deployments.',
      challengeText2: 'The solution required deep indoor penetration, minimal power consumption, and cost-effective data plans for infrequent, small data transmissions typical of utility metering applications.',
      solution1Title: 'Low-data Connectivity',
      solution1Desc: 'Deployed specialized Low-data SIM cards optimized for ultra-low power consumption, enabling 10+ year battery life with superior indoor coverage and penetration.',
      solution2Title: 'Optimized Data Plans',
      solution2Desc: 'Implemented cost-effective data plans tailored for infrequent, small-packet transmissions typical of smart meter communications, reducing operational costs by 50%.',
      solution3Title: 'Automated Provisioning',
      solution3Desc: 'Streamlined SIM activation and device onboarding through automated provisioning APIs, reducing deployment time and eliminating manual configuration errors.',
      result1: 'Tens of thousands meters deployed with 10+ year battery life achieved',
      result2: '50% cost reduction compared to previous connectivity solution',
      result3: '99% read success rate even in challenging indoor environments',
      result4: 'Zero-touch deployment through automated provisioning APIs',
      ctaTitle: 'Need Low-Power IoT Connectivity?',
      ctaDesc: 'Discover how low-data cards can power your utility or smart city deployment',
    },
    GPS: {
      badge: 'Global Supply-Chain Visibility',
      title: 'GPS & Multi-Modal Tracking Success Story',
      shortTitle: "GPS Tracking",
      subtitle: 'Sea · Land · Air – One SKU, One Map, One Truth',
      metric1: 'Active Trackers',
      metric2: 'Countries Crossed',
      metric3: 'Platform Uptime',
      metric4: '<2s auth',
      highlight: '100% compliance',
      challengeText1: 'A leading electric vehicle manufacturer needed a reliable, scalable IoT connectivity solution to support their rapidly expanding fleet across Europe and Asia. Their existing connectivity infrastructure was fragmented across multiple carriers, leading to coverage gaps, inconsistent performance, and complex billing.',
      challengeText2: "The company required real-time vehicle diagnostics, over-the-air updates, and fleet management capabilities across 62 countries, with seamless roaming and carrier-grade reliability.",
      solution1Title: 'Tele2 Global Roaming SIM Cards',
      solution1Desc: 'Deployed Tele2 SIM cards with multiple roaming providers support, enabling automatic network switching for optimal coverage and cost efficiency across all regions.',
      solution2Title: 'Network Security',
      solution2Desc: 'Implemented enterprise-grade security to protect sensitive data and ensure seamless network handover.',
      solution3Title: 'Real-Time Management Portal',
      solution3Desc: 'Provided comprehensive connectivity management platform with real-time diagnostics, usage analytics, and automated alerting for proactive issue resolution.',
      result1: '99% uptime across all markets, exceeding SLA requirements',
      result2: '40% reduction in connectivity costs through optimized carrier selection',
      result3: 'Real-time diagnostics enabling predictive maintenance and reduced downtime via Tele2\'s Control Center',
      ctaTitle: 'Need GPS & Multi-Modal Tracking Service?',
      ctaDesc: "Let's discuss Global Supply-Chain Visibility IoT solutions",
    },
    medical: {
      badge: 'Healthcare',
      title: 'Medical Device Success Story',
      shortTitle: "Medical Device",
      subtitle: 'FDA & MIIT certified connectivity for global medical IoT deployment',
      metric1: 'FDA Approved',
      metric2: 'MIIT Certified',
      metric3: 'Dual Market',
      metric4: 'FDA + MIIT dual approval',
      highlight: 'Regulatory cleared',
      challengeText1: 'A medical device manufacturer needed to launch their connected patient monitoring system in both US and China markets simultaneously. The challenge involved navigating complex regulatory requirements while maintaining secure, HIPAA-compliant data transmission.',
      challengeText2: 'Different certification processes, network requirements, and data privacy regulations in each market created significant deployment complexity and risk of delays.',
      solution1Title: 'Regulatory Compliance Package',
      solution1Desc: 'Provided end-to-end support for FDA certification in US and MIIT type-approval in China, including technical documentation, network compliance proof, and certification guidance.',
      solution2Title: 'HIPAA-Compliant Connectivity',
      solution2Desc: 'Implemented private APN with encrypted connections meeting HIPAA requirements for Protected Health Information (PHI), ensuring patient data security across both markets.',
      solution3Title: 'Dual-Market SIM Solution',
      solution3Desc: 'Deployed unified eUICC SIM cards certified for both markets, eliminating the need for separate inventory and simplifying supply chain management.',
      result1: 'FDA approval and MIIT certification achieved within 6 months',
      result2: 'Simultaneous launch in US and China markets',
      result3: '100% HIPAA compliance with zero data breach incidents',
      result4: '30% faster time-to-market compared to competitors',
      ctaTitle: 'Ready to Launch Your Medical IoT Device?',
      ctaDesc: "Let's navigate regulatory compliance together for your healthcare IoT deployment",
    },
    mobility: {
      badge: 'Transportation',
      title: 'Shared Mobility Platform Success Story',
      shortTitle: "Shared Mobility",
      subtitle: 'DLT-compliant SMS campaigns driving user engagement in India',
      metric1: 'Messages/Month',
      metric2: 'DLT Compliance',
      metric3: 'Open Rate',
      metric4: '30M messages/month',
      highlight: '48hr deployment',
      challengeText1: 'A major shared mobility platform struggled with SMS campaign delivery in India due to complex DLT (Distributed Ledger Technology) regulations introduced by TRAI. Their promotional messages were being blocked, causing significant drops in user engagement and booking rates.',
      challengeText2: 'The platform needed rapid DLT registration, template approval, and sender ID whitelisting across multiple telecom operators to restore their marketing capabilities.',
      solution1Title: 'Complete DLT Onboarding',
      solution1Desc: 'Handled end-to-end DLT registration process including entity onboarding, template creation and approval, sender ID registration, and operator whitelisting.',
      solution2Title: 'Template Optimization',
      solution2Desc: 'Optimized SMS templates for maximum approval rates while maintaining marketing effectiveness, creating pre-approved template library for quick campaign deployment.',
      solution3Title: 'Multi-Operator Integration',
      solution3Desc: 'Integrated with all major Indian telecom operators ensuring consistent delivery rates and comprehensive coverage across the entire user base.',
      result1: '5M+ compliant SMS messages delivered monthly',
      result2: '100% DLT compliance with zero message blocking',
      result3: '40% improvement in SMS open rates',
      result4: '48-hour DLT setup for new campaign templates',
      ctaTitle: 'Need DLT-Compliant SMS in India?',
      ctaDesc: "Let's get your promotional campaigns running at full capacity",
    },
  },
};

// Chinese Simplified translations
const zhTranslations = {
  header: {
    home: '首页',
    partners: '合作伙伴',
    solutions: '解决方案',
    about: '关于我们',
    products: '产品',
    caseStudies: '案例研究',
    contact: '联系我们',
    login: '登录',
    getStarted: '开始使用',
    loading: '加载中...',
    noPartners: '暂无合作伙伴',
    iotConnectivity: '物联网连接',
    m2mPlatform: 'M2M平台',
    deviceManagement: '设备管理',
    analytics: '分析与洞察',
    customSolutions: '定制解决方案',
  },
  hero: {
    companyName: 'ISL - 并蓄信息技术服务有限公司',
    title1: '全球物联网与M2M连接',
    title2: '本地化工程',
    description: '在中国、印度、欧盟、美国和新加坡为数百万物联网设备提供运营商级可靠服务',
    iotSolutions: '物联网解决方案',
    m2mConnectivity: 'M2M连接',
    support: '24/7支持',
    scrollDown: '向下滚动',
  },
  about: {
    title: '全球物联网与M2M连接，本地化工程',
    subtitle1: '我们弥合全球覆盖与本地专业知识之间的差距，提供跨大陆的无缝物联网连接。',
    subtitle2: 'ISL通过运营商级可靠性和区域合规性为数百万连接设备提供动力，受到全球企业的信赖。',
    globalOperations: '全球运营',
    active: '活跃',
    ourValues: '我们的价值观',
    compliance: '合规性',
    value1: '可靠性：99.9%正常运行时间SLA，由冗余网络支持',
    value2: '本地专业知识：国内法规遵从和支持',
    value3: '创新：为不断发展的需求提供尖端物联网解决方案',
    value4: '透明：明确定价，无隐藏费用',
    miit: '工信部',
    miitDesc: '中国工信部批准',
    trai: 'TRAI',
    traiDesc: '印度电信管理局',
    ce: 'CE',
    ceDesc: '欧洲合格认证',
    fcc: 'FCC',
    fccDesc: '美国联邦认证',
    ctaTitle: '准备好全球连接了吗？',
    ctaDesc: '预约15分钟探讨电话，讨论您的物联网连接需求',
    bookCall: '预约探讨电话',
    china: '中国',
    chinaLocation: '北京',
    india: '印度',
    indiaLocation: '孟买和德里',
    eu: '欧盟',
    euLocation: '阿姆斯特丹',
    usa: '美国',
    usaLocation: '纽约',
    singapore: '新加坡',
    singaporeLocation: '新加坡',
  },
  cta: {
    title: '让我们连接您的物联网生态系统',
    description: '通过ISL开始您的全球物联网部署。联系我们获取个性化咨询。',
    namePlaceholder: '您的姓名',
    emailPlaceholder: '电子邮件地址',
    companyPlaceholder: '公司名称',
    submitButton: '请求咨询',
    reachUs: '或直接联系我们：',
    contactInfo: 'INCLUSIVE-SALES@inclusive.com.cn',
  },
  solutions: {
    title: '企业物联网解决方案',
    subtitle: '为您的物联网部署需求量身定制的端到端连接解决方案',
    globalIotSim: '全球物联网SIM卡',
    globalIotSimDesc: '支持eUICC的SIM卡，可在180多个国家实现无缝全球漫游',
    globalIotSimBenefit: '一张SIM卡，全球连接',
    privateApn: '专用APN + VPN + InterCloud',
    privateApnDesc: '专用网络隧道，为敏感物联网数据提供企业级安全',
    privateApnBenefit: '设备的银行级安全',
    smsVoice: '物联网短信和语音',
    smsVoiceDesc: '用于设备管理和关键警报的双向短信和语音通道',
    smsVoiceBenefit: '实时设备通信',
    chinaApproval: '中国型号核准和白名单',
    chinaApprovalDesc: '完整的工信部认证和网络白名单服务，进入中国市场',
    chinaApprovalBenefit: '快速进入中国市场',
    indiaDlt: '印度DLT入驻',
    indiaDltDesc: '完整的DLT注册捆绑包，符合TRAI规范的促销短信活动',
    indiaDltBenefit: '48小时内启动短信活动',
    learnMore: '了解更多',
  },
  products: {
    title: '灵活的定价计划',
    subtitle: '选择适合您物联网部署规模的计划',
    prepaid: '预付费',
    postpaid: '后付费',
    popular: '热门',
    getStarted: '开始使用',
    customSolution: '需要定制解决方案？',
    contactSales: '联系我们的销售团队',
    starterPack: '入门SIM套餐',
    volumePlans: '批量计划',
    oemWhiteLabel: 'OEM白标SIM',
    managementPortal: '管理门户',
    perSim3Months: '每张SIM / 3个月',
    basedOnVolume: '基于批量',
    perSimMoq: '每张SIM（10K+起订量）',
    withAllPlans: '所有计划包含',
    included: '包含',
    custom: '定制',
  },
  footer: {
    companyDesc: '全球企业物联网M2M连接解决方案的领先提供商。',
    services: '服务',
    iotConnectivity: '物联网连接',
    m2mSolutions: 'M2M解决方案',
    networkSecurity: '网络安全',
    dataManagement: '数据管理',
    company: '公司',
    aboutUs: '关于我们',
    careers: '职业',
    partners: '合作伙伴',
    contact: '联系我们',
    contactUs: '联系我们',
    whatsappSupport: 'WhatsApp支持',
    chinaOffice: '中国办公室',
    chinaLocation: '中国上海',
    indiaOffice: '印度办公室',
    indiaLocation: '印度孟买和德里',
    euOffice: '欧盟办公室',
    euLocation: '荷兰阿姆斯特丹',
    copyright: '© 2025 并蓄信息技术服务有限公司。保留所有权利。',
  },
  caseStudy: {
    title: '客户成功案例',
    subtitle: '看看其他企业如何在他们的物联网方案中使用并蓄的服务',
    backToHome: '返回首页',
    theChallenge: '项目挑战',
    ourSolution: '我们的解决方案',
    results: '成果展示',
    contactUs: '联系我们',
    ev: {
      badge: '汽车行业',
      title: '电动汽车远程信息处理成功案例',
      shortTitle: "电动汽车远程信息处理",
      subtitle: '横跨欧洲和亚洲的实时车辆诊断与车队管理',
      metric1: '活跃SIM卡',
      metric2: '国家数量',
      metric3: '运行时间',
      metric4: '180个国家',
      highlight: '99%运行时间',
      challengeText1: '一家领先的电动汽车制造商需要可靠、可扩展的物联网连接解决方案，以支持其在欧洲和亚洲快速扩张的车队。其现有连接基础设施分散在多个运营商之间，导致覆盖范围存在空白、性能不稳定且计费复杂。',
      challengeText2: '该公司需要在100多个国家实现实时车辆诊断、空中软件更新和车队管理功能，并要求无缝漫游和运营商级别的可靠性。',
      solution1Title: '全球多国漫游运营商支持的SIM卡',
      solution1Desc: '部署支持eUICC的SIM卡，支持多国漫游，可在所有运营区域自动切换网络以实现最佳覆盖和成本效益。',
      solution2Title: '私有APN与VPN安全',
      solution2Desc: '采用企业级安全标准，通过专用私有APN和VPN隧道保护敏感的车辆数据，确保空中软件更新的安全性。',
      solution3Title: '实时管理平台',
      solution3Desc: '提供全面的连接管理平台，具备实时诊断、使用情况分析和自动告警功能，实现主动问题解决。',
      result1: '在所有市场实现99%的运行时间，超出SLA要求',
      result2: '通过优化运营商选择，连接成本降低40%',
      result3: '无需更改基础设施即可无缝扩展至120万辆车辆',
      result4: '实时诊断实现预测性维护，减少停机时间',
      ctaTitle: '准备好扩展您的物联网车队了吗？',
      ctaDesc: '让我们探讨ISL如何为您的互联汽车解决方案提供动力',
    },
    smartMeter: {
      badge: '能源行业',
      title: '智能电表原始设备制造商成功案例',
      shortTitle: "智能电表原始设备制造商",
      subtitle: '低功耗计量解决方案，延长设备生命周期',
      metric1: 'NB-IoT SIM卡',
      metric2: '电池寿命',
      metric3: '成本降低',
      metric4: '80万张NB-IoT SIM卡 • 10年电池寿命',
      highlight: '成本降低50%',
      challengeText1: '一家智能电表制造商需要超低功耗连接解决方案，以支持远程公用事业计量部署的10年以上电池寿命。传统蜂窝连接对于大规模电表部署而言功耗过高且成本昂贵。',
      challengeText2: '该解决方案需要深度室内穿透、最小功耗，以及针对公用事业计量应用中典型的不频繁小数据传输的成本效益数据套餐。',
      solution1Title: 'NB-IoT连接',
      solution1Desc: '部署专为超低功耗优化的NB-IoT SIM卡，实现10年以上电池寿命，并提供卓越的室内覆盖和穿透能力。',
      solution2Title: '优化数据套餐',
      solution2Desc: '实施针对智能电表通信典型的不频繁小数据包传输量身定制的成本效益数据套餐，将运营成本降低50%。',
      solution3Title: '自动化配置',
      solution3Desc: '通过自动化配置API简化SIM卡激活和设备上线流程，减少部署时间并消除手动配置错误。',
      result1: '部署80万个电表，实现10年以上电池寿命',
      result2: '与之前的连接解决方案相比，成本降低50%',
      result3: '即使在具有挑战性的室内环境中，读取成功率也达到99.8%',
      result4: '通过自动化配置API实现零接触部署',
      ctaTitle: '需要低功耗物联网连接吗？',
      ctaDesc: '探索NB-IoT如何为您的公用事业或智慧城市部署提供动力',
    },
    GPS: {
      badge: '全球供应链可视化',
      title: 'GPS与多式联运追踪成功案例',
      shortTitle: "GPS追踪",
      subtitle: '海运·陆运·空运——一个SKU，一张地图，一个真相',
      metric1: '活跃追踪器',
      metric2: '跨境国家',
      metric3: '平台运行时间',
      metric4: 'PCI-DSS认证 • 私有APN • <2秒认证',
      highlight: '100%合规',
      challengeText1: '一家领先的电动汽车制造商需要可靠、可扩展的物联网连接解决方案，以支持其在欧洲和亚洲快速扩张的车队。其现有连接基础设施分散在多个运营商之间，导致覆盖范围存在空白、性能不稳定且计费复杂。',
      challengeText2: "该公司需要在62个国家实现实时车辆诊断、空中软件更新和车队管理功能，并要求无缝漫游和运营商级别的可靠性。",
      solution1Title: '全球多国漫游运营商支持的SIM卡',
      solution1Desc: '部署支持eUICC的SIM卡，支持多国漫游，可在所有运营区域自动切换网络以实现最佳覆盖和成本效益。',
      solution2Title: '私有APN与VPN安全',
      solution2Desc: '采用企业级安全标准，通过专用私有APN和VPN隧道保护敏感的车辆数据，确保空中软件更新的安全性。',
      solution3Title: '实时管理平台',
      solution3Desc: '提供全面的连接管理平台，具备实时诊断、使用情况分析和自动告警功能，实现主动问题解决。',
      result1: '在所有市场实现99%的运行时间，超出SLA要求',
      result2: '通过优化运营商选择，连接成本降低40%',
      result3: '无需更改基础设施即可无缝扩展至4万辆车辆',
      result4: '实时诊断实现预测性维护，减少停机时间',
      ctaTitle: '需要GPS与多式联运追踪服务吗？',
      ctaDesc: "让我们探讨全球供应链可视化物联网解决方案",
    },
    medical: {
      badge: '医疗健康',
      title: '医疗设备成功案例',
      shortTitle: "医疗设备",
      subtitle: '通过FDA和MIIT认证的连接方案，支持全球医疗物联网部署',
      metric1: 'FDA认证',
      metric2: 'MIIT认证',
      metric3: '双市场',
      metric4: 'FDA + MIIT双重认证',
      highlight: '通过法规审批',
      challengeText1: '一家医疗设备制造商需要同时在美国和中国市场推出其联网患者监测系统。挑战在于在满足复杂法规要求的同时，保持符合HIPAA标准的安全数据传输。',
      challengeText2: '不同市场的认证流程、网络要求和数据隐私法规存在差异，导致部署复杂性显著增加并存在延迟风险。',
      solution1Title: '法规合规套餐',
      solution1Desc: '为美国FDA认证和中国工信部入网许可提供端到端支持，包括技术文档、网络合规证明和认证指导。',
      solution2Title: '符合HIPAA标准的连接',
      solution2Desc: '实施满足HIPAA对受保护健康信息要求的私有APN加密连接，确保两个市场的患者数据安全。',
      solution3Title: '双市场SIM卡解决方案',
      solution3Desc: '部署经两个市场认证的统一eUICC SIM卡，消除单独库存需求并简化供应链管理。',
      result1: '6个月内完成FDA批准和工信部认证',
      result2: '在美国和中国市场同步推出',
      result3: '100%符合HIPAA标准，零数据泄露事件',
      result4: '与竞争对手相比，上市时间缩短30%',
      ctaTitle: '准备好推出您的医疗物联网设备了吗？',
      ctaDesc: "让我们共同为您的医疗健康物联网部署应对法规合规要求",
    },
    mobility: {
      badge: '交通运输',
      title: '共享出行平台成功案例',
      shortTitle: "共享出行",
      subtitle: '符合DLT规范的短信营销活动，提升印度用户参与度',
      metric1: '月发送量',
      metric2: 'DLT合规',
      metric3: '打开率',
      metric4: '每月3000万条短信',
      highlight: '48小时部署',
      challengeText1: '一家大型共享出行平台因印度电信管理局引入的复杂DLT法规而在短信营销活动投放方面遇到困难。其促销短信被拦截，导致用户参与度和预订率显著下降。',
      challengeText2: '该平台需要快速完成DLT注册、模板审批和跨多个电信运营商的发送者ID白名单添加，以恢复其营销能力。',
      solution1Title: '完整的DLT入驻服务',
      solution1Desc: '处理端到端DLT注册流程，包括实体入驻、模板创建与审批、发送者ID注册和运营商白名单添加。',
      solution2Title: '模板优化',
      solution2Desc: '在保持营销效果的同时优化短信模板以获得最高审批率，创建预审批模板库以便快速部署营销活动。',
      solution3Title: '多运营商集成',
      solution3Desc: '与所有主要印度电信运营商集成，确保持续的送达率和覆盖整个用户群的全面覆盖。',
      result1: '每月发送500多万条合规短信',
      result2: '100%符合DLT规范，零短信拦截',
      result3: '短信打开率提升40%',
      result4: '新营销活动模板48小时内完成DLT设置',
      ctaTitle: '需要在印度发送符合DLT规范的短信吗？',
      ctaDesc: "让您的促销活动全面恢复运行",
    },
  },
};
